spring.application.name=CareervexJobPortal
server.port = 8080

# ─── JWT secret key ──────────────────────────────────────────────────────────────
jwt.secret = JqzCQQRbGNMdOpJ6BbEEnuF2rxCzMWPAzDg4AcDayom
# dZ8YgYRIZelEMkMDyaOu9PiL6khHIVhKskbxQZUdDdG                                     |
jwt.expiration = 86400000
# ─────────────────────────────────────────────────────────────────────────────────

# ─── PostgreSQL ──────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/JobPortal
spring.datasource.username=postgres
spring.datasource.password=9944
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.open-in-view=false